### ISSUE TITLE
Allow views to introspect on style additions

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#256]
![image](https://cloud.githubusercontent.com/assets/204989/12381362/8a2c4f4a-bd3d-11e5-89ec-7163dd1b31f6.png)

```js
view Main {
  <StyleEater style={{fontSize: 30 }} />
  $StyleEater = { color: 'blue' }
}

view StyleEater {
  <h1>{JSON.stringify(view.props.style)}</h1>
}
```
expected:
```json
{"fontSize":30, "color": "blue" }
```

@liron00 really wants this

**Comment by liron00** [comment]
Yup

**Comment by natew** [comment]
This is a tough on re: hot reloading.

Basically once you have styles in javascript, you now have to hot reload in javascript every time you change. Hard to get around this one though.

We could: debounce update javascript, so when you drag/color pick it just does css, but after a moment catches up.

Downside: if you are relying on style introspection your components will break during that time.

**Comment by liron00** [comment]
The "breakage" will be more of a lag / janky style rather than an error,
and seems like a totally fine compromise.

--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by natew** [comment]
Actually I can see a way that doesn't seem bad to me. Before i was worried about huge changed because this would affect hot reloads altogether but I think we can solve this without touching any babel stuff.

Basically: We can at runtime set the style property just by merging Flint.staticStyles with the prop styles (dynamic ones). Will attempt patch soon just noting here.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
